# Generated by Django 4.0.5 on 2022-08-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapping',
            unique_together={('name', 'key')},
        ),
    ]
